puzzle_dict = {
    'empty': 
    [[None, None, None, None, None, None, None, None, None],
     [None, None, None, None, None, None, None, None, None],
     [None, None, None, None, None, None, None, None, None],
     [None, None, None, None, None, None, None, None, None],
     [None, None, None, None, None, None, None, None, None],
     [None, None, None, None, None, None, None, None, None],
     [None, None, None, None, None, None, None, None, None],
     [None, None, None, None, None, None, None, None, None],
     [None, None, None, None, None, None, None, None, None]],
    'easy':
    [[7, None, None, 1, None, None, None, None, 8],
     [None, 3, 6, 2, None, 8, 7, None, None],
     [8, None, 4, None, 6, None, None, None, None],
     [None, 8, None, None, 5, None, 2, 1, None],
     [None, None, 2, 4, None, 7, 3, None, None],
     [None, 9, 1, None, 8, None, None, 7, None],
     [None, None, None, None, 9, None, 8, None, 5],
     [None, None, 8, 5, None, 3, 6, 9, None],
     [5, None, None, None, None, 4, None, None, 7]], 
    'medium':
    [[None, 9, None, None, 6, 1, None, 3, None],
     [None, None, 6, 3, None, None, None, 1, None],
     [4, None, None, None, None, None, 9, None, 8],
     [None, None, None, None, None, 9, 3, 5, 1],
     [None, None, None, None, 8, None, None, None, None],
     [2, 5, 1, 6, None, None, None, None, None],
     [3, None, 9, None, None, None, None, None, 5],
     [None, 4, None, None, None, 6, 2, None, None],
     [None, 7, None, 5, 2, None, None, 9, None]] , 
    'hard':
    [[3, None, None, 6, None, None, 4, None, None],
     [None, 6, None, None, None, None, None, 2, None],
     [None, None, 2, 8, None, None, 5, None, 6],
     [4, None, None, None, 8, None, 2, 6, None],
     [None, None, None, 7, None, 3, None, None, None],
     [None, 9, 1, None, 6, None, None, None, 5],
     [6, None, 9, None, None, 2, 3, None, None],
     [None, 8, None, None, None, None, None, 1, None],
     [None, None, 7, None, None, 8, None, None, 4]],
    'hardest': 
    [[8, None, None, None, None, None, None, None, None],
     [None, None, 3, 6, None, None, None, None, None],
     [None, 7, None, None, 9, None, 2, None, None],
     [None, 5, None, None, None, 7, None, None, None],
     [None, None, None, None, 4, 5, 7, None, None],
     [None, None, None, 1, None, None, None, 3, None],
     [None, None, 1, None, None, None, None, 6, 8],
     [None, None, 8, 5, None, None, None, 1, None],
     [None, 9, None, None, None, None, 4, None, None]]
    }

